#!/bin/bash

OUTPUT_IMAGE="/tmp/lockscreen.png"
TMP_IMAGE="/tmp/wallpaper-converted.jpg"
WALLPAPER="$HOME/Pictures/Wallpapers/wallpaper.jpg"

convert $WALLPAPER -resize 1920x1200^ -extent 1920x1200 -blur 0x12 $TMP_IMAGE
convert -extent 3840x1200 -composite $TMP_IMAGE $TMP_IMAGE -geometry +1920+0 $OUTPUT_IMAGE

i3lock -i $OUTPUT_IMAGE -t
rm $OUTPUT_IMAGE
