#!/bin/bash

cp system-config/00-keyboard.conf /etc/X11/xorg.conf.d/00-keyboard.conf
chown root:root /etc/X11/xorg.conf.d/00-keyboard.conf

cp system-config/logid.cfg /etc/logid.cfg
chown root:root /etc/logid.cfg

