#!/bin/python

import subprocess
import re

process = subprocess.Popen(['dropbox-cli', 'status'], stdout=subprocess.PIPE)
output, error = process.communicate()

if b'Up to date' in output:
    print('')

else:
    print('')

