#!/bin/python
# Based on script from https://github.com/Jvanrhijn/polybar-spotify
# Interface documentation at https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html

import dbus

def truncate(title, trunclen = 25):
    if len(title) > trunclen:
        title = title[0:trunclen] + '...'
        if ('(' in title) and (')' not in title):
            title += ')'
    return title

try:
    session_bus = dbus.SessionBus()
    spotify_bus = session_bus.get_object("org.mpris.MediaPlayer2.spotify", "/org/mpris/MediaPlayer2")

    spotify_properties = dbus.Interface(spotify_bus, "org.freedesktop.DBus.Properties")

    is_playing = (spotify_properties.Get("org.mpris.MediaPlayer2.Player", "PlaybackStatus") == 'Playing')

    metadata = spotify_properties.Get("org.mpris.MediaPlayer2.Player", "Metadata")
    artist = metadata['xesam:artist'][0]
    title = truncate(metadata['xesam:title'])

    if is_playing:
        print("{} - {}".format(artist, title))
    else:
        print("")
except:
    print("")
