#!/bin/bash

STEAM_PATH="/home/svendcs/.local/share/Steam/ubuntu12_32/steam"

if pgrep -f "$STEAM_PATH" > /dev/null; then
  echo -e "\uf1b6" # Steam icon
  #echo -e "\uf1b7" # Square Steam icon
else
  echo ""
fi
